from logic_layer import WorkerLL, AirplaneLL, FlightLL, FlightRouteLL, VoyageLL


# functions that UI layer calls --
class UIAPI:
    def __init__(self):
        self.workerLL = WorkerLL.WorkerLL()
        self.flightLL = FlightLL.FlightLL()
        self.airplaneLL = AirplaneLL.AirplaneLL()
        self.flightRouteLL = FlightRouteLL.FlightRouteLL()
        self.voyageLL = VoyageLL.VoyageLL()

    def get_airplanes(self):
        [print(instance) for instance in self.airplaneLL.get_airplane_list()]

    #
    # plane related
    #
    def newPlaneRequest(self, myList):
        """"""
        returnString = self.airplaneInstance.createNewPlane(myList)
        return returnString

    def viewXplane(self, idToFind):
        returnData = self.airplaneInstance.getXplane(idToFind)
        return returnData

    def viewAllPlanes(self):
        returnData = self.airplaneInstance.getAllFlights()
        return returnData

    #
    # worker related
    #
    def createNewWorker(self, workerList):
        """takes in workerList, but ID, Active and Available are not in this list so they have to be automatically filled by you guys"""
        return = self.workerLL.createNewWorker(workerList)
    #
    # flight related
    #
    def createNewFlight(self, flightList):
        """flightList is only Airplane reg, Origin ID, Destination ID and Departure time, all other info must be generated by you guys"""
        return = self.flightLL.createNewFlight(flightList)

    def viewCertainFlight(self, flightNumber):
        """we give you a flightnumber and you need to return a error if it does not exist, otherwise you return the instance"""
        return = self.flightLL.getCertainflight(flightNumber)

    def viewAllFlights(self):
        """give us all flight instances, would be nice if we can get 5 at a time or something instead of all at once"""
        return = self.flightLL.getAllFlights()

    def viewActiveFlights(self):
        """give us all flight instances that dont have the status cancelled"""
        return = self.flightLL.getActiveFlights()

    def viewCancelledFlights(self):
        """give us all flight instances that have the status cancelled"""
        return = self.flightLL.getCancelledFlights()
    
    def updateFlightStatus(self, newStatus):
        """we give you a new status and you update the instance and the csv file according to that"""
        return = self.flightLL.updateFlightStatus()
    
    def updateFlightDepartureTime(self, newDepartureTime):
        """we give you a new departure time and you update the instance and the csv file according to that"""
        return = self.flightLL.updateFlightDepartureTime()
    #
    # voyage related
    #

    #
    # flight route related
    #


# ++++++++++ Test Case ++++++++++
# UIAPI = UIAPI()
# UIAPI.get_airplanes()
