class FlightClass():
    def __init__(self, AirplaneReg = "", Origin = "", Destination = "", DepartureTime = "", FlightStatus = "On Schedule", FlightID = "", FlightNumber = "NA", FlightRouteID = "", TravelTime = "", ArrivalTime = ""):
        self.AirplaneReg = AirplaneReg#important
        self.Origin = Origin#important
        self.Destination = Destination #important
        self.DepartureTime = DepartureTime #important
        self.FlightStatus = FlightStatus #default is on Schedule
        self.FlightID = FlightID#Generated by a function
        self.FlightNumber = FlightNumber #Generated by a function
        self.FlightRouteID = FlightRouteID #Generated by a function
        self.TravelTime = TravelTime #found in flightRoute
        self.ArrivalTime = ArrivalTime # genereated by flightRoute
        
    
    def __str__(self):
        return '''Flight number: {}
Airplane reg: {}
Flight status: {}
Travel time: {}
Departure time: {}
Origin: {}
Arrival time: {}
Destination: {}'''.format(self.FlightNumber, self.AirplaneReg, self.FlightStatus, self.TravelTime, self.DepartureTime, self.Origin, self.ArrivalTime, self.Destination)
